# Generated by Django 3.1 on 2020-05-18 14:02
from django.conf import settings
from django.db import migrations

FLATPAGES = [
    {
    'title': "About",
    'url': '/about/',
    'content':None,
    },
]

def add_flatpages_data(apps, scheme_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    Site = apps.get_model('sites', 'Site')
    site_id = getattr(settings, 'SITE_ID', 1)
    current_site = Site.objects.get(pk=site_id)
    for page in FLATPAGES:
        new_page = FlatPage.objects.create(title=page['title'], url=page['url'], content=page['content'])
        new_page.sites.add(current_site)

def remove_flatpages_data(apps, scheme_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    for page in FLATPAGES:
        page_obj = FlatPage.objects.get(title=page['title'], url=page['url'], content=page['content'])
        page_obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_site_data'),
        ('flatpages', '0001_initial')
    ]

    operations = [
        migrations.RunPython(add_flatpages_data, remove_flatpages_data)
    ]
