# Generated by Django 3.1 on 2020-05-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_newslink_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='newslink', unique_together=set([('slug', 'startup')])),
    ]
