# Generated by Django 3.1 on 2020-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_newslin_unique_together_slug_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslink',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='tags',
            field=models.ManyToManyField(blank=True, to='organizer.Tag'),
        ),
    ]
