# Generated by Django 3.1 on 2020-05-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='profile.jpg', upload_to=''),
        ),
    ]
